Timesheet/Controllers/HourCodesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Timesheet.Models;

namespace Timesheet.Controllers
{
    public class HourCodesController : Controller
    {
        private TimesheetEntities db = new TimesheetEntities();

        // GET: HourCodes
        public ActionResult Index(string searchString)
        {
            return View(db.HourCodes.Where(x => x.CodeDescription.Contains(searchString) || searchString == null).ToList());
        }

        // GET: HourCodes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HourCode hourCode = db.HourCodes.Find(id);
            if (hourCode == null)
            {
                return HttpNotFound();
            }
            return View(hourCode);
        }

        // GET: HourCodes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HourCodes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CodeID,CodeDescription,CodeValue")] HourCode hourCode)
        {
            bool errorFlag = false;
            if(String.IsNullOrEmpty(hourCode.CodeDescription) || db.HourCodes.ToList().Any(s => s.CodeDescription == hourCode.CodeDescription))
            {
                ViewBag.ValidateHourCode = String.IsNullOrEmpty(hourCode.CodeDescription) ? "Code description field is required" : $"\"There already exists code description: {hourCode.CodeDescription}\"";
                errorFlag = true;
            }
            if(String.IsNullOrEmpty(hourCode.CodeValue.ToString()))
            {
                ViewBag.ValidateCodeValue = "Code value field is required";
                errorFlag = true;
            }
            if (ModelState.IsValid)
            {
                if(!errorFlag)
                {
                db.HourCodes.Add(hourCode);
                db.SaveChanges();
                return RedirectToAction("Index");
                }
            }

            return View(hourCode);
        }

        // GET: HourCodes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HourCode hourCode = db.HourCodes.Find(id);
            if (hourCode == null)
            {
                return HttpNotFound();
            }
            return View(hourCode);
        }

        // POST: HourCodes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CodeID,CodeDescription,CodeValue")] HourCode hourCode)
        {
            bool errorFlag = false;
            if (String.IsNullOrEmpty(hourCode.CodeDescription))
            {
                ViewBag.ValidateHourCode = "Code description field is required";
                errorFlag = true;
            }
            if (String.IsNullOrEmpty(hourCode.CodeValue.ToString()))
            {
                ViewBag.ValidateCodeValue = "Code value field is required";
                errorFlag = true;
            }
            if (ModelState.IsValid)
            {
                if(!errorFlag)
                {
                    db.Entry(hourCode).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(hourCode);
        }

        // GET: HourCodes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HourCode hourCode = db.HourCodes.Find(id);
            if (hourCode == null)
            {
                return HttpNotFound();
            }
            return View(hourCode);
        }

        // POST: HourCodes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HourCode hourCode = db.HourCodes.Find(id);
            db.HourCodes.Remove(hourCode);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Timesheet/Controllers/Job_RoleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Timesheet.Models;

namespace Timesheet.Controllers
{
    public class Job_RoleController : Controller
    {
        private TimesheetEntities db = new TimesheetEntities();

        // GET: Job_Role
        public ActionResult Index(string searchString)
        {
            return View(db.Job_Role.Where(x => x.JobDescription.Contains(searchString) || searchString == null).ToList());
        }

        // GET: Job_Role/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job_Role job_Role = db.Job_Role.Find(id);
            if (job_Role == null)
            {
                return HttpNotFound();
            }
            return View(job_Role);
        }

        // GET: Job_Role/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Job_Role/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JobRoleID,JobDescription")] Job_Role job_Role)
        {
            bool errorFlag = false;
            if(String.IsNullOrEmpty(job_Role.JobDescription) || db.Job_Role.ToList().Any(s => s.JobDescription == job_Role.JobDescription))
            {
                ViewBag.ValidateJobRole = String.IsNullOrEmpty(job_Role.JobDescription) ? "Job role field is required" : $"Job role \"{job_Role.JobDescription}\" already exists";
                errorFlag = true;
            }
            
            if (ModelState.IsValid)
            {
                if(!errorFlag)
                {
                    db.Job_Role.Add(job_Role);
                    db.SaveChanges();
                    return RedirectToAction("Index");   
                }

            } 
                return View(job_Role);

        }

        // GET: Job_Role/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job_Role job_Role = db.Job_Role.Find(id);
            if (job_Role == null)
            {
                return HttpNotFound();
            }
            return View(job_Role);
        }

        // POST: Job_Role/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JobRoleID,JobDescription")] Job_Role job_Role)
        {
            bool errorFlag = false;
            if(String.IsNullOrEmpty(job_Role.JobDescription))
            {
                ViewBag.ValidateJobRole = "Job description field is required";
                errorFlag = true;
            }
            if (ModelState.IsValid)
            {
                if(!errorFlag)
                {
                db.Entry(job_Role).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
                }
            }
            return View(job_Role);
        }

        // GET: Job_Role/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job_Role job_Role = db.Job_Role.Find(id);
            if (job_Role == null)
            {
                return HttpNotFound();
            }
            return View(job_Role);
        }

        // POST: Job_Role/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job_Role job_Role = db.Job_Role.Find(id);
            db.Job_Role.Remove(job_Role);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Timesheet/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Timesheet.Models;

namespace Timesheet.Controllers
{
    public class UsersController : Controller
    {
        private TimesheetEntities db = new TimesheetEntities();

        public ActionResult Index(string searchString)
        { 
            var users = db.Users.Include(u => u.Job_Role);
            return View(db.Users.Where(x => x.FirstName.Contains(searchString) || searchString == null).ToList());
        }

        // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            ViewBag.JobRoleID = new SelectList(db.Job_Role, "JobRoleID", "JobDescription");
            ViewBag.JobDescription = new SelectList(db.Job_Role, "JobRoleID", "JobDescription");

            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserID,FirstName,LastName,Email,Phone,JobDescription,Password,confirmPassword,JobRoleID")] User user)
        {
            bool errorFlag = false;
            if(String.IsNullOrEmpty(user.Email) || db.Users.ToList().Any(s => s.Email == user.Email))
            {
                ViewBag.ValidateEmail = String.IsNullOrEmpty(user.Email) ? "Email field is required": $"There already exists an email: \"{ user.Email}\"";
                errorFlag = true;
            }
            if (String.IsNullOrEmpty(user.FirstName))
            {
                ViewBag.ValidateFirstName = "First name field is required";
                errorFlag = true;
            }
            if (String.IsNullOrEmpty(user.LastName))
            {
                ViewBag.ValidateLastName = "Last name field is required";
                errorFlag = true;
            }


            if (ModelState.IsValid)
            {
                if(!errorFlag)
                {
                    //Hashing password 
                    //user.Password = Crypto.Hash(user.Password);
                    //Hash confirm password
                    //user.confirmPassword = Crypto.Hash(user.confirmPassword);
                    db.Users.Add(user);
                    db.SaveChanges();
                    return RedirectToAction("Index");

                }

            }
            ViewBag.JobRoleID = new SelectList(db.Job_Role, "JobRoleID", "JobDescription", user.JobRoleID);
            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.JobRoleID = new SelectList(db.Job_Role, "JobRoleID", "JobDescription", user.JobRoleID);
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserID,FirstName,LastName,Email,Phone,JobRoleID, Password, confirmPassword")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.JobRoleID = new SelectList(db.Job_Role, "JobRoleID", "JobDescription", user.JobRoleID);
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Timesheet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" style="height: 100px;">
            <div class="navbar-header">
                @Html.ActionLink("TIMECARD", "Login", "Home",
                                   new { area = "" }, new { @class = "navbar-brand", @style = "line-height: 60px; font-size: 18px;" })
            </div>
        </div>
    </div>

    @*Side Menu*@

    <div class="container body-content">
        <div class="d-flex" id="wrapper">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Team 7</p>
        </footer>
    </div>
    <script>
        $(document).ready(function () {
            $('[datatoggle="tooltip"]').tooltip();

            
        });

    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Timesheet/Views/Shared/_PartialDocLoc.cshtml
<div class="container">
    <ul class="nav nav-tabs">
        <li><a data-toggle="tab" href="#menu2">@Html.ActionLink("User", "Index", "Users")</a></li>
        <li><a class="active" data-toggle="tab" href="#home">@Html.ActionLink("Doctors", "Index", "Doctors")</a></li>
        <li><a data-toggle="tab" href="#menu2">@Html.ActionLink("Locations", "Index", "Locations")</a></li>
    </ul>
    <p class="text-right">
        <a href="@Url.Action("Logout", "Home")">Log out</a>
    </p>
    <br />
    <div class="tab-content">
        <div id="menu2" class="tab-pane fade">
        </div>
        <div id="home" class="tab-pane fade in active">
        </div>
        <div id="menu1" class="tab-pane fade">
        </div>
    </div>
</div>

Timesheet/Views/Shared/_PartialLogout.cshtml
<style>
    .logout {
        margin-top: 50px;
    }
</style>
<div>
    <p class="text-right logout">
        <a href="@Url.Action("Logout", "Home")">Log out</a>
    </p>
</div>

Timesheet/Views/Shared/_PartialNavbar.cshtml
<div class="container">
    <ul class="nav nav-tabs">
        <li><a class="active" data-toggle="tab" href="#home">@Html.ActionLink("User", "Index", "Users")</a></li>
        <li><a data-toggle="tab" href="#menu1">@Html.ActionLink("TimeCard", "Index", "Doctors")</a></li>
        <li><a data-toggle="tab" href="#menu2">@Html.ActionLink("Reports", "Index", "Schedules")</a></li>
        <li><a data-toggle="tab" href="#menu3">@Html.ActionLink("Job Roles", "Index", "Job_Role")</a></li>
        <li><a data-toggle="tab" href="#menu4">@Html.ActionLink("Sectors", "Index", "Sectors")</a></li>
        <li><a data-toggle="tab" href="#menu5">@Html.ActionLink("Hour Code", "Index", "HourCodes")</a></li>

    </ul>
    <p class="text-right">
        <a href="@Url.Action("Logout", "Home")">Log out</a>
    </p>
    <div class="tab-content">
        <div id="home" class="tab-pane fade in active">
        </div>
        <div id="menu1" class="tab-pane fade">
        </div>
        <div id="menu2" class="tab-pane fade">
        </div>
        <div id="menu3" class="tab-pane fade">
        </div>
        <div id="menu4" class="tab-pane fade">
        </div>
        <div id="menu5" class="tab-pane fade">
        </div>
    </div>
</div>