Timesheet/Models/Location.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.Doctors = new HashSet<Doctor>();
        }
    
        public int LocationID { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> SectionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual Sector Sector { get; set; }
    }
}

Timesheet/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Timesheet.Models;

namespace Timesheet.Controllers
{
    public class LocationsController : Controller
    {
        private TimesheetEntities db = new TimesheetEntities();

        // GET: Locations
        public ActionResult Index(string searchString)
        {
            var locations = db.Locations.Include(l => l.Sector);
            return View(db.Locations.Where(x => x.LocationName.Contains(searchString) || searchString == null).ToList());
        }

        // GET: Locations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // GET: Locations/Create
        public ActionResult Create()
        {
            ViewBag.SectionID = new SelectList(db.Sectors, "SectionID", "SectorName");
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LocationID,LocationName,SectionID")] Location location)
        {
            try
            {
                ViewBag.strSlectedSector = location.SectionID;
                if (ModelState.IsValid)
                {
                    //if (!String.IsNullOrEmpty(location.LocationName))
                    //{
                        if (!(String.IsNullOrEmpty(location.LocationName) || db.chkLocationNameExist(location.LocationName)))
                        {
                            db.Locations.Add(location);
                            db.SaveChanges();
                            return RedirectToAction("Index");
                        }
                        else
                            ViewBag.ValLocationName = String.IsNullOrEmpty(location.LocationName) ? "You have not entered a value for Location" : $"There already exist a Location named \"{location.LocationName}\"";
                    //}
                    //else
                }
                ViewBag.ValSectorName = "Select a value for Sector Name";
                ViewBag.SectionID = new SelectList(db.Sectors, "SectionID", "SectorName", location.SectionID);
            }
            catch (Exception ex)
            {
                ViewBag.SectionID = new SelectList(db.Sectors, "SectionID", "SectorName", location.SectionID);
                ViewBag.ValSummary = $"An error occured while creating this Location \n{ex.Message}";
            }


            return View(location);
        }

        // GET: Locations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            ViewBag.SectionID = new SelectList(db.Sectors, "SectionID", "SectorName", location.SectionID);
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "LocationID,LocationName,SectionID")] Location location)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var context = new TimesheetEntities())
                    {
                        Location loc = context.Locations.Find(location.LocationID);
                        if (loc != null)
                        {
                            if (!(String.IsNullOrEmpty(location.LocationName) || (context.chkLocationNameExist(location.LocationName) && loc.LocationName != location.LocationName)))
                            {
                                db.Entry(location).State = EntityState.Modified;
                                db.SaveChanges();
                                return RedirectToAction("Index");
                            }
                            else
                                ViewBag.ValLocationName = String.IsNullOrEmpty(location.LocationName) ? "You have not entered a value for Location" : $"There already exist a Location named \"{location.LocationName}\"";
                        }
                        else
                            ViewBag.LocationName = $"This location could not be found in the database";
                    }
                }
                ViewBag.SectionID = new SelectList(db.Sectors, "SectorName", "SectorName", location.SectionID);
            }
            catch (Exception ex)
            {
                ViewBag.SectionID = new SelectList(db.Sectors, "SectorName", "SectorName", location.SectionID);
                ViewBag.ValLocationName = $"An error occured while updating this Location \n{ex.Message}";
            }
            return View(location);
        }

        // GET: Locations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Location location = db.Locations.Find(id);
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Timesheet/Views/Locations/Create.cshtml
@model Timesheet.Models.Location

@{
    ViewBag.Title = "Create New Location";
}
@Html.Partial("_PartialLogout")

<h2>Create new location</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, ViewBag.ValSummary as string, new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.LocationID, "Location", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LocationName, new { htmlAttributes = new { @class = "form-control" } })
            <br />
            @Html.ValidationMessageFor(model => model.LocationName, ViewBag.ValLocationName as string, new { @class = "field-validation-error" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SectionID, "Sector", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("SectionID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.SectionID, ViewBag.ValSectorName as string, new { @class = "field-validation-error" })
        </div>
    </div>

    <div class="form-actions no-color">
        <input type="submit" value="Create" class="btn btn-default" />
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script>
        document.getElementById("SectorName").value = "@ViewBag.strSlectedSector";
        document.getElementById("SectorName").classList.add('form-control');
</script>

Timesheet/Views/Locations/Delete.cshtml
@model Timesheet.Models.Location

@{ ViewBag.Title = $" Delete {Model.LocationName}"; }

@Html.Partial("_PartialLogout")

<h2>Are you sure you want to delete <b>@Model.LocationName</b>?</h2>

<div>
    <hr />
    <dl class="dl-horizontal well">
        <dt>
            Location Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationName)
        </dd>

        <dt>
            Sector Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sector.SectorName)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
@Html.AntiForgeryToken()

                <div class="form-actions no-color">

                    <input type="submit" value="Delete" class="btn btn-default" />
                </div>}
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Timesheet/Views/Locations/Details.cshtml
@model Timesheet.Models.Location

@{ ViewBag.Title = $"{Model.LocationName} Location Details"; }

@Html.Partial("_PartialLogout")

<h2> <b>@Model.LocationName</b> Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal well">
        <dt>
            Location Name
        </dt>

        <dd>
            @Html.ActionLink(Model.LocationName, "Edit", new { id = Model.LocationID }, new { datatoggle = "tooltip", title = $"Click to edit {Model.LocationName} location" })
        </dd>

        <dt>
            Sector Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sector.SectorName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Timesheet/Views/Locations/Edit.cshtml
@model Timesheet.Models.Location

@{ ViewBag.Title = $"Edit {Model.LocationName} Location"; }

@Html.Partial("_PartialLogout")

<h2>Edit <b>@Model.LocationName</b> Location</h2>



@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, ViewBag.ValLocationName as string, new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.LocationID)

                    <div class="form-group">
                        @Html.LabelFor(model => model.LocationName, "Location Name", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LocationName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LocationName, ViewBag.ValLocationName as string, new { @class = "field-validation-error" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SectionID, "Sector Name", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("SectionID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.SectionID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Timesheet/Views/Locations/Index.cshtml
@model IEnumerable<Timesheet.Models.Location>

@{
    ViewBag.Title = "Index";
}
@Html.Partial("_PartialDocLoc")

<style>
    a.first-name {
        color: #333333;
        font-weight: bold;
    }

    #reset {
        background-color: #56baed;
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        text-transform: uppercase;
        font-size: 13px;
        -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
        box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
        -webkit-border-radius: 5px 5px 5px 5px;
        border-radius: 5px 5px 5px 5px;
        margin: 5px 20px 40px 20px;
        -webkit-appearance: button;
        cursor: pointer;
    }

        #reset > a {
            text-decoration: none;
            color: white;
        }

        #reset:focus {
            background-color: #fff;
            border-bottom: 2px solid #5fbae9;
        }

        #reset:active {
            -moz-transform: scale(0.95);
            -webkit-transform: scale(0.95);
            -o-transform: scale(0.95);
            -ms-transform: scale(0.95);
            transform: scale(0.95);
        }

        #reset:hover {
            background-color: #39ace7;
        }
</style>

<h2>Location</h2>

@using (Html.BeginForm("Index", "Locations", FormMethod.Get))
{

<div>
    <b>Search By:</b>
    Location Name 
    <br />
    @Html.TextBox("searchString")
    <input type="submit" value="Search" />
    <button id="reset">@Html.ActionLink("Reset", "Index")</button>
</div>
<table class="table table-striped table-hover">
    <p class="text-right">
        @Html.ActionLink("Add Location", "Create")
    </p>
    <tr>
        <th>
            @Html.DisplayName("Location")
        </th>
        <th>
            @Html.DisplayName("Sector")
        </th>
        <th></th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="8">No record was found</td>
        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
<tr>
    <td>
        @Html.ActionLink(item.LocationName, "Details", new { id = item.LocationID }, new { datatoggle = "tooltip", title = $"Click for {item.LocationName} details" })
        @*@Html.ActionLink(Model.LocationName, "Edit", new { id = Model.LocationID }, new { datatoggle = "tooltip", title = $"Click to edit {Model.LocationName} location" })*@
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Sector.SectorName)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.LocationID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.LocationID })
    </td>
</tr>}
                }
</table>
}
@*@model ienumerable<timesheet.models.location>

    @{
        viewbag.title = "index";
    }

    <style>
        th {
            background-color: black;
            color: white;
        }

        a:hover {
            color: blue;
        }
    </style>
    <h2>index</h2>
    <p>
        @html.actionlink("create new", "create")
    </p>
    <table class="table">
        <tr>
            <th>
                @html.displaynamefor(model => model.locationname)
            </th>
            <th>
                @html.displaynamefor(model => model.sector.sectorname)
            </th>
            <th></th>
        </tr>

        @foreach (var item in model)
        {
            <tr>
                <td>
                    @html.displayfor(modelitem => item.locationname)
                </td>
                <td>
                    @html.displayfor(modelitem => item.sector.sectorname)
                </td>
                <td>
                    @html.actionlink("edit", "edit ", new { id = item.locationid },new { htmlattributes =  new { @class = "fa fa-edit" } }) |
                    @html.actionlink("details", "details ", new { id = item.locationid }, new  { @class = "fa fa-info-circle" }) |
                    @html.actionlink("delete", "delete ", new { id = item.locationid }, new { @class = "fa fa-times-circle" })
                </td>
            </tr>
        }

    </table>*@