Timesheet/Models/Sector.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sector()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public string SectorName { get; set; }
        public int SectionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Locations { get; set; }
    }
}

Timesheet/Controllers/SectorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Timesheet.Models;

namespace Timesheet.Controllers
{
    public class SectorsController : Controller
    {
        private TimesheetEntities db = new TimesheetEntities();

        // GET: Sectors
        public ActionResult Index(string searchString)
        {
            return View(db.Sectors.Where(x => x.SectorName.Contains(searchString) || searchString == null).ToList());
        }

        // GET: Sectors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sector sector = db.Sectors.Find(id);
            if (sector == null)
            {
                return HttpNotFound();
            }
            return View(sector);
        }

        // GET: Sectors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sectors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SectorName,SectionID")] Sector sector)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (!(String.IsNullOrEmpty(sector.SectorName) || db.chkSectorNameExist(sector.SectorName)))
                    {
                        db.Sectors.Add(sector);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                        ViewBag.ErrorValidation = String.IsNullOrEmpty(sector.SectorName) ? "You have not entered a value for Sector" : $"There already exist a Sector named \"{sector.SectorName}\"";
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorValidation = $"An error occured while creating this Sector \n{ex.Message}";
            }

            return View(sector);
        }

        // GET: Sectors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sector sector = db.Sectors.Find(id);
            if (sector == null)
            {
                return HttpNotFound();
            }
            return View(sector);
        }

        // POST: Sectors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SectorName,SectionID")] Sector sector, string oldSectorName)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var context = new TimesheetEntities())
                    {
                        Sector sec = context.Sectors.Find(sector.SectionID);
                        if (sec != null)
                        {
                            if (!(String.IsNullOrEmpty(sector.SectorName) || (context.chkSectorNameExist(sector.SectorName) && sec.SectorName != sector.SectorName)))
                            {
                                db.Entry(sector).State = EntityState.Modified;
                                db.SaveChanges();
                                //db.updateSector(oldSectorName, sector.SectorName);
                                return RedirectToAction("Index");
                            }
                            else
                                ViewBag.ErrorValidation = String.IsNullOrEmpty(sector.SectorName) ? "You have not entered a value for Sector" : $"There already exist a Sector named \"{sector.SectorName}\"";
                        }
                        else
                            ViewBag.ErrorValidation = $"This sector ID {sector.SectionID} could not be found in the database";
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.ErrorValidation = $"An error occured during update {ViewBag.oldSectorName}. ({ex.Message})";
            }
            return View(sector);
        }

        // GET: Sectors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sector sector = db.Sectors.Find(id);
            if (sector == null)
            {
                return HttpNotFound();
            }
            return View(sector);
        }

        // POST: Sectors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sector sector = db.Sectors.Find(id);
            db.Sectors.Remove(sector);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Timesheet/Views/Sectors/Create.cshtml
@model Timesheet.Models.Sector

@{
    ViewBag.Title = "Create New Sector";
}
@Html.Partial("_PartialLogout")
<h2>Create new sector </h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.SectorName, "Sector Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SectorName, new { htmlAttributes = new { @class = "form-control" } })
            <br />
            @Html.ValidationMessageFor(model => model.SectorName, ViewBag.ErrorValidation as string, new { @class = "field-validation-error" })
        </div>
    </div>

    <div class="form-actions no-color">
        <input type="submit" value="Save" class="btn btn-default" />
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Timesheet/Views/Sectors/Delete.cshtml
@model Timesheet.Models.Sector

@{ ViewBag.Title = $" Delete {Model.SectorName}"; }

@Html.Partial("_PartialLogout")

<h2>Are you sure you want to delete <b>@Model.SectorName</b> sector?</h2>

<div>
    <hr />
    <dl class="dl-horizontal well">
        <dt>
            Sector Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SectorName)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
@Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" />
                </div>}
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Timesheet/Views/Sectors/Details.cshtml
@model Timesheet.Models.Sector

@{ ViewBag.Title = $"{Model.SectorName} Details"; }

@Html.Partial("_PartialLogout")

<h2> <b>@Model.SectorName</b> Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal well">
        <dt>
            Sector Name
        </dt>

        <dd>
            @Html.ActionLink(Model.SectorName, "Edit", new { id = Model.SectionID }, new { datatoggle = "tooltip", title = $"Click to edit {Model.SectorName} sector" })
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Timesheet/Views/Sectors/Edit.cshtml
@model Timesheet.Models.Sector

@{
    ViewBag.Title = $"Edit {Model.SectorName} Sector";

}

@Html.Partial("_PartialLogout")

<h2>Edit <b>@Model.SectorName</b> Sector</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    <input type="hidden" name="oldSectorName" value="@Model.SectorName" />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.SectorName, "Sector Name",htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SectorName, new { htmlAttributes = new { @class = "form-control" } })
            <br />
            @Html.ValidationMessageFor(model => model.SectorName, ViewBag.ErrorValidation as string, new { @class = "field-validation-error" })
        </div>
    </div>

    @Html.HiddenFor(model => model.SectionID)

    <div class="form-actions no-color">
        <input type="submit" value="Save" class="btn btn-default" />
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Timesheet/Views/Sectors/Index.cshtml
@model IEnumerable<Timesheet.Models.Sector>

@{ ViewBag.Title = "Index"; }

@Html.Partial("_PartialNavbar")
<style>
    a.first-name {
        color: #333333;
        font-weight: bold;
    }

    #reset {
        background-color: #56baed;
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        text-transform: uppercase;
        font-size: 13px;
        -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
        box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
        -webkit-border-radius: 5px 5px 5px 5px;
        border-radius: 5px 5px 5px 5px;
        margin: 5px 20px 40px 20px;
        -webkit-appearance: button;
        cursor: pointer;
    }

        #reset > a {
            text-decoration: none;
            color: white;
        }

        #reset:focus {
            background-color: #fff;
            border-bottom: 2px solid #5fbae9;
        }

        #reset:active {
            -moz-transform: scale(0.95);
            -webkit-transform: scale(0.95);
            -o-transform: scale(0.95);
            -ms-transform: scale(0.95);
            transform: scale(0.95);
        }

        #reset:hover {
            background-color: #39ace7;
        }
</style>

<h2>Sector</h2>

@using (Html.BeginForm("Index", "Sectors", FormMethod.Get))
{
<div>
    <b>Search By:</b>
    Sector
    <br />
    @Html.TextBox("searchString")
    <input type="submit" value="Search" />
    <button id="reset">@Html.ActionLink("Reset", "Index")</button>
</div>
<table class="table table-striped table-hover">
    <p class="text-right">
        @Html.ActionLink("Add Sector", "Create")
    </p>
    <tr>
        <th>
            @Html.DisplayName("Sector")
        </th>
        <th></th>
    </tr>
    @if (Model.Count() == 0)
    {
<tr>
    <td colspan="8">No record was found</td>
</tr> }
                else
                {
                    foreach (var item in Model)
                    {
<tr>
    <td>
        @Html.ActionLink(item.SectorName, "Details", new { id = item.SectionID }, new { datatoggle = "tooltip", title = $"Click for details" })
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.SectionID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.SectionID })
    </td>
</tr>}
                }
</table>
}