Timesheet/Models/Doctor.cs
namespace Timesheet.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Schedules = new HashSet<Schedule>();
        }

        public Nullable<int> FileNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Sex { get; set; }
        public string Phone { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public int DoctorId { get; set; }
        public int LocationID { get; set; }
        public string Address { get; set; }
        public int GenderID { get; set; }
        public string GenderName { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }

    }
}

Timesheet/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Timesheet.Models
{
    public class DoctorsController : Controller
    {
        private TimesheetEntities db = new TimesheetEntities();
        //Gender selection
        List<Doctor> genderList = new List<Doctor>
        {
            new Doctor { GenderName= "Male", GenderID = 1},
            new Doctor { GenderName= "Female", GenderID = 2}
        };

        // GET: Doctors
        public ActionResult Index(string searchString)
        {
            var doctors = db.Doctors.Include(d => d.Location);
            return View(doctors.Where(x => x.FirstName.Contains(searchString) || searchString == null).ToList());

        }

        // GET: Doctors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // GET: Doctors/Create
        public ActionResult Create()
        {
            ViewBag.Sex = new SelectList(genderList, "GenderName", "GenderName");
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName");
            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FirstName,LastName,Phone,Email,LocationID,Sex, Address")] Doctor doctor)
        {
            bool errorFlag = false;
            if(String.IsNullOrEmpty(doctor.Email) || db.Doctors.ToList().Any(s => s.Email == doctor.Email))
            {
                ViewBag.ValidateEmail = String.IsNullOrEmpty(doctor.Email) ? "Email field is required" : $"There already exist an email: \"{doctor.Email}\"";
                errorFlag = true;
            }
            if(String.IsNullOrEmpty(doctor.FirstName))
            {
                ViewBag.ValidateFirstName = "First name field is required";
                errorFlag = true;
            }
            if(String.IsNullOrEmpty(doctor.LastName))
            {
                ViewBag.ValidateLastName = "Last name field is required";
                errorFlag = true;
            }

            if (ModelState.IsValid)
            {
                if(!errorFlag)
                {
                    //db.Doctors.Add(doctor);
                    db.Doctors.Add(doctor);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            ViewBag.Sex = new SelectList(genderList, "GenderName", "GenderName", doctor.Sex);
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", doctor.LocationID);
            return View(doctor);
        }

        // GET: Doctors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", doctor.LocationID);
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FirstName,LastName,Sex,Phone,Email,DoctorId,LocationID,Address")] Doctor doctor)
        {
            bool errorFlag = false;
            if(String.IsNullOrEmpty(doctor.Email))
            {
                ViewBag.ValidateEmail = "Email address field is required";
                errorFlag = true;
            }
            if(String.IsNullOrEmpty(doctor.FirstName))
            {
                ViewBag.ValidateFirstName = "First name field is required";
                errorFlag = true;
            }
            if(String.IsNullOrEmpty(doctor.LastName))
            {
                ViewBag.ValidateLastName = "Last name field is required";
                errorFlag = true;
            }

            if (ModelState.IsValid)
            {
                if(!errorFlag)
                {
                    db.Entry(doctor).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName", doctor.LocationID);
            return View(doctor);
        }

        // GET: Doctors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            ViewBag.Sex = new SelectList(genderList, "GenderName", "GenderName", doctor.Sex);
            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Doctor doctor = db.Doctors.Find(id);
            db.Doctors.Remove(doctor);
            db.SaveChanges();
            ViewBag.Sex = new SelectList(genderList, "GenderName", "GenderName", doctor.Sex);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Timesheet/Controllers/SchedulesController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using Timesheet.Models;
using PagedList.Mvc;
using System.Net.Mail;
using System.Text;

namespace Timesheet.Controllers
{
    public class SchedulesController : Controller
    {
        private TimesheetEntities db = new TimesheetEntities();

        // GET: Schedules
        public ActionResult Index(string searchBy, string search, int? page, string sortBy)
        {
            ViewBag.SortNameParameter = string.IsNullOrEmpty(sortBy) ? "Name asc" : "";
            ViewBag.SortFileNumberParameter = string.IsNullOrEmpty(sortBy) ? "FileNumber" : "";

            var schedules = db.Schedules.Include(s => s.Doctor).Include(s => s.HourCode).AsQueryable();

            if (searchBy == "FileNumber")
            {
                int id = Convert.ToInt32(search);
                schedules = schedules.Where(x => x.Doctor.FileNumber == id || search == null);
                //return View(schedules.ToList().ToPagedList(page ?? 1, 5));
            }
            else 
            {
                schedules = schedules.Where(x => x.Doctor.FirstName.StartsWith(search) || search == null);
                //return View(schedules.ToList().ToPagedList(page ?? 1, 5));
            } 

            switch (sortBy)
            {
                case "Name asc":
                    schedules = schedules.OrderBy(x => x.Doctor.FirstName);
                    break;
                case "FileNumber":
                    schedules = schedules.OrderBy(x => x.Doctor.FileNumber);
                    break;
            }


            return View(schedules.ToList().ToPagedList(page ?? 1, 5));


        }

        // GET: Schedules/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedules.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }

        // GET: Schedules/Create
        public ActionResult Create(int id)
        {
            Doctor dr = db.Doctors.Single(emp => emp.DoctorId == id);
            TempData["DoctorID"] = dr.DoctorId;
            ViewBag.dr = dr;
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "LocationName");
            ViewBag.HourCodeId = new SelectList(db.HourCodes, "CodeID", "CodeDescription");
            ViewBag.Amount = new SelectList(db.HourCodes, "CodeID", "CodeValue");
            return View();
        }

        // POST: Schedules/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LocationID,HourCodeId")] Schedule schedule, FormCollection data)
        {
            int hi = Convert.ToInt32(data["HourCodeId"]);
            HourCode hr = db.HourCodes.Single(emp => emp.CodeID == hi);
            string timein = data["Date"] + " " + data["Time_In"];
            string timeout = data["Date"] + " " + data["Time_Out"];
            schedule.Time_In = DateTime.ParseExact(timein, "yyyy-MM-dd HH:mm", null);
            schedule.Time_Out = DateTime.ParseExact(timeout, "yyyy-MM-dd HH:mm", null);
            schedule.DoctorID = Convert.ToInt32(TempData["DoctorID"]);
            schedule.Amount = hr.CodeValue;
            if (ModelState.IsValid)
            {
                db.Schedules.Add(schedule);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DoctorID = new SelectList(db.Doctors, "DoctorId", "FirstName", schedule.DoctorID);
            ViewBag.LocationID = new SelectList(db.Locations, "LocationId", "LocationName", schedule.LocationID);
            ViewBag.HourCodeId = new SelectList(db.HourCodes, "CodeID", "CodeID", schedule.HourCodeId);
            return View(schedule);
        }

        // GET: Schedules/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedules.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            ViewBag.DoctorID = new SelectList(db.Doctors, "DoctorId", "FirstName", schedule.DoctorID);
            ViewBag.HourCodeId = new SelectList(db.HourCodes, "CodeID", "CodeDescription", schedule.HourCodeId);
            return View(schedule);
        }

        // POST: Schedules/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ScheduleID,DoctorID,LocationID,UserID,Time_In,Time_Out,HourCodeId,Amount")] Schedule schedule)
        {
            if (ModelState.IsValid)
            {
                db.Entry(schedule).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DoctorID = new SelectList(db.Doctors, "DoctorId", "FirstName", schedule.DoctorID);
            ViewBag.HourCodeId = new SelectList(db.HourCodes, "CodeID", "CodeDescription", schedule.HourCodeId);
            return View(schedule);
        }

        // GET: Schedules/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedules.Find(id);
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }

        // POST: Schedules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Schedule schedule = db.Schedules.Find(id);
            db.Schedules.Remove(schedule);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //Send Email
       //public JsonResult SendMailToDoctor()
       // {
       //     //Doctor dr = db.Doctors.Single(emp => emp.DoctorId == id);

       //     bool result = false;
       //     result = SendEmail("Saynegrojas@gmail.com", "Scheduled date", "<p>Scheduled</p>");
       //     return Json(result, JsonRequestBehavior.AllowGet);
       // }
        
       // public bool SendEmail(string toEmail, string subject, string body)
       // {

       //     try
       //     {
       //         string senderEmail = System.Configuration.ConfigurationManager.AppSettings["SenderEmail"].ToString();
       //         string senderPassword = System.Configuration.ConfigurationManager.AppSettings["SenderPassword"].ToString();

       //         SmtpClient client = new SmtpClient("smtp.gmail.com", 587);
       //         client.EnableSsl = true;
       //         client.Timeout = 100000;
       //         client.DeliveryMethod = SmtpDeliveryMethod.Network;
       //         client.UseDefaultCredentials = false;
       //         client.Credentials = new NetworkCredential(senderEmail, senderPassword);

       //         MailMessage mail = new MailMessage(senderEmail, toEmail, subject, body);
       //         mail.IsBodyHtml = true;
       //         mail.BodyEncoding = UTF8Encoding.UTF8;

       //         client.Send(mail);

       //         return true;
       //     } catch (Exception e)
       //     {
       //         return false;
       //     }
       // } 
    }
}

Timesheet/Views/Doctors/Create - Copy.cshtml
@model Timesheet.Models.Doctor

@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h2>Create</h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.FileNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FileNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FileNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sex, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sex, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Timesheet/Views/Doctors/Create.cshtml
@model Timesheet.Models.Doctor

@{
    ViewBag.Title = "Create";
}

@Html.Partial("_PartialLogout")

<h2>Create a Doctor</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Location", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("LocationID", ViewData["LocationID"] as IEnumerable<SelectListItem>, "-- Select a location --", htmlAttributes: new { @class = "form-control", @required = "required" })
            @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            <br />
            @Html.ValidationMessageFor(model => model.FirstName, ViewBag.ValidateFirstName as string, new { @class = "field-validation-error" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            <br />
            @Html.ValidationMessageFor(model => model.LastName, ViewBag.ValidateLastName as string, new { @class = "field-validation-error" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Sex, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Sex", ViewData["Sex"] as IEnumerable<SelectListItem>, "-- Select a Sex --", htmlAttributes: new { @class = "form-control", @required = "required" })
            @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })

        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, ViewBag.ValidateEmail as string, new { @class = "field-validation-error" })
        </div>
    </div>

        <div class="form-actions no-color">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Timesheet/Views/Doctors/Delete.cshtml
@model Timesheet.Models.Doctor

@{ ViewBag.Title = $" Delete Dr. {Model.FirstName}"; }

@Html.Partial("_PartialLogout")

<h2>Are you sure you want to delete Dr. <b>@Model.LastName</b>?</h2>
<div>
    <hr />
    <dl class="dl-horizontal well">
        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.LocationName)
        </dd>
        <dt>
            @Html.DisplayName("First Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayName("Last Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sex)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
@Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" />
                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                </div>}
</div>

Timesheet/Views/Doctors/Details.cshtml
@model Timesheet.Models.Doctor

@{ ViewBag.Title = $"Dr. {Model.LastName} Details"; }

@Html.Partial("_PartialLogout")

<h2>Dr. <b>@Model.LastName </b>'s</b> Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal well">
        <dt>
            @Html.DisplayNameFor(model => model.Location.LocationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.LocationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sex)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sex)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DoctorId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Timesheet/Views/Doctors/Index.cshtml
@model IEnumerable<Timesheet.Models.Doctor>

@{ ViewBag.Title = "Index"; }
@Html.Partial("_PartialDocLoc")

<style>
    a.first-name {
        color: #333333;
        font-weight: bold;
    }

    #reset {
        background-color: #56baed;
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        text-transform: uppercase;
        font-size: 13px;
        -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
        box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
        -webkit-border-radius: 5px 5px 5px 5px;
        border-radius: 5px 5px 5px 5px;
        margin: 5px 20px 40px 20px;
        -webkit-appearance: button;
        cursor: pointer;
    }

        #reset > a {
            text-decoration: none;
            color: white;
        }

        #reset:focus {
            background-color: #fff;
            border-bottom: 2px solid #5fbae9;
        }

        #reset:active {
            -moz-transform: scale(0.95);
            -webkit-transform: scale(0.95);
            -o-transform: scale(0.95);
            -ms-transform: scale(0.95);
            transform: scale(0.95);
        }

        #reset:hover {
            background-color: #39ace7;
        }
</style>

<h2>Select a Doctor</h2>

@using (Html.BeginForm("Index", "Doctors", FormMethod.Get))
{

<div>
    <b>Search By:</b>
    Name 
    <br />
    @Html.TextBox("searchString")
    <input type="submit" value="Search" />
    <button id="reset">@Html.ActionLink("Reset", "Index")</button>
</div>
<table class="table table-striped table-hover">
    <p class="text-right">
    @Html.ActionLink("Add Doctor", "Create")
</p>
    <tr> 
        <th>
            @Html.DisplayName("Doctor Email")
        </th>
        <th>
            @Html.DisplayName("First Name")
        </th>
        <th>
            @Html.DisplayName("Last Name")
        </th>
        <th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="8">No record was found</td>
        </tr>
    }
    else
    {
    foreach (var item in Model)
    {
<tr>
    <td>
        @Html.ActionLink(Convert.ToString(item.Email), "Create", "Schedules", new { id = item.DoctorId }, new { datatoggle = "tooltip", title = $"Click to schedule {item.FirstName} {item.LastName}" })
        @*@Html.ActionLink(location, "Edit", new { id = item.LocationID }, new { datatoggle = "tooltip", title = $"Click to select {item.LocationName} location" })*@

    </td>
    <td>
        @*@Html.ActionLink(Convert.ToString(item.FirstName), "Create", "Schedules", new { id = item.DoctorId }, new { datatoggle = "tooltip", title = $"Click to set a schedule" })*@
        @Html.DisplayFor(modelItem => item.FirstName)

    </td>
    <td>
        @*@Html.ActionLink(Convert.ToString(item.LastName), "Create", "Schedules", new { id = item.DoctorId }, new { datatoggle = "tooltip", title = $"Click to set a schedule" })*@
        @Html.DisplayFor(modelItem => item.LastName)


    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.DoctorId }) |
        @Html.ActionLink("Details", "Details", new { id = item.DoctorId }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.DoctorId })
    </td>
</tr>
    }
}
</table>
}